export const FETCH_GET_COUPON_ACTION = "FETCH_GET_COUPON_ACTION";
export const FETCH_GET__DETAIL_COUPON_ACTION = "FETCH_GET__DETAIL_COUPON_ACTION";
export const FETCH_ADD_COUPON_ACTION = "FETCH_ADD_COUPON_ACTION";
export const FETCH_UPDATE_COUPON_ACTION = "FETCH_UPDATE_COUPON_ACTION";
export const FETCH_DELETE_COUPON_ACTION = "FETCH_DELETE_COUPON_ACTION";
export const FETCH_HISTORY_COUPON_ACTION = "FETCH_HISTORY_COUPON_ACTION";
