export const FETCH_GET_INTERNAL_USER = "FETCH_GET_INTERNAL_USER";
export const FETCH_GET_DETAIL_INTERNAL_USER = "FETCH_GET_DETAIL_INTERNAL_USER";
export const FETCH_CHANGE_PASSWORD = "FETCH_CHANGE_PASSWORD";
export const FETCH_UPLOAD_AVATAR = "FETCH_UPLOAD_AVATAR";
