export const FETCH_GET_PRODUCT = "FETCH_GET_PRODUCT";
export const FETCH_GET_PRODUCT_DETAIL = "FETCH_GET_PRODUCT_DETAIL";
export const FETCH_GET_All_ROLE_ACTIVE = "FETCH_GET_All_ROLE_ACTIVE";
export const FETCH_GET_DETAIL_ROLE = "FETCH_GET_DETAIL_ROLE";
