export const FETCH_GET_CATEGORY_NEWS = "FETCH_GET_CATEGORY_NEWS";
export const FETCH_GET_ALL_CATEGORY_NEWS = "FETCH_GET_ALL_CATEGORY_NEWS";
export const FETCH_ADD_NEWS = "FETCH_ADD_NEWS";
export const FETCH_UPDATE_NEWS = "FETCH_UPDATE_NEWS";
export const FETCH_DELETE_NEWS = "FETCH_DELETE_NEWS";
