export const FETCH_GET_NEWS = "FETCH_GET_NEWS";
export const FETCH_GET_DETAIL_NEWS = "FETCH_GET_DETAIL_NEWS";
export const FETCH_ADD_NEWS_ARTICLE = "FETCH_ADD_NEWS_ARTICLE";
export const FETCH_UPDATE_NEWS_ARTICLE = "FETCH_UPDATE_NEWS_ARTICLE";
export const FETCH_DELETE_NEWS_ARTICLE = "FETCH_DELETE_NEWS_ARTICLE";
