export const FETCH_GET_ROLE = "FETCH_GET_ROLE";
export const FETCH_GET_ROLE_ACTIVE = "FETCH_GET_ROLE_ACTIVE";
export const FETCH_GET_All_ROLE_ACTIVE = "FETCH_GET_All_ROLE_ACTIVE";
export const FETCH_GET_DETAIL_ROLE = "FETCH_GET_DETAIL_ROLE";
