import { ArticlesType, BannersType, ProductsType } from "types/api-response-type";

export const fakeHotDealProducts: ProductsType = [
  {
    productCode: "001",
    productName: "S'Mone Claire Elastin",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/sample_product.webp",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "002",
    productName: "S Vera Aloe Vera Cleansing Hand Gel",
    pv: 1500,
    memberPrice: 990,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/hotdeal2.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "003",
    productName: "Hand Protect Alcohol Spray Baby Cute (50 ML)",
    pv: 900,
    memberPrice: 750,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/hotdeal3.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "004",
    productName: "S'Mone Delecious Sun Screen",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/hotdeal4.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
];

export const fakeFlashSaleProducts: ProductsType = [
  {
    productCode: "001",
    productName: "S'Mone Claire Elastin",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/hotdeal1.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "002",
    productName: "S Vera Aloe Vera Cleansing Hand Gel",
    pv: 1500,
    memberPrice: 990,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/flashsale1.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "003",
    productName: "Hand Protect Alcohol Spray Baby Cute (50 ML)",
    pv: 900,
    memberPrice: 750,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/flashsale2.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "004",
    productName: "S'Mone Delecious Sun Screen",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/hotdeal2.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
];

export const fakeSkinProducts1: ProductsType = [
  {
    productCode: "001",
    productName: "S'Mone Claire Elastin",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/skin1.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "002",
    productName: "S Vera Aloe Vera Cleansing Hand Gel",
    pv: 1500,
    memberPrice: 990,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/skin2.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "003",
    productName: "Hand Protect Alcohol Spray Baby Cute (50 ML)",
    pv: 900,
    memberPrice: 750,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/skin3.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "004",
    productName: "S'Mone Delecious Sun Screen",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/skin4.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
];

export const fakeSkinProducts2: ProductsType = [
  {
    productCode: "001",
    productName: "S'Mone Claire Elastin",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/skin21.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "002",
    productName: "S Vera Aloe Vera Cleansing Hand Gel",
    pv: 1500,
    memberPrice: 990,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/skin22.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "003",
    productName: "Hand Protect Alcohol Spray Baby Cute (50 ML)",
    pv: 900,
    memberPrice: 750,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/skin23.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
  {
    productCode: "004",
    productName: "S'Mone Delecious Sun Screen",
    pv: 3000,
    memberPrice: 1500,
    personalPrice: 2200,
    weight: 1,
    categoryId: "1",
    categoryName: "1",
    sdate: "2021-01-01",
    edate: "2021-01-01",
    flag: "",
    media: [
      {
        url: "/assets/images/flashsale2.png",
        fileType: "image",
        position: 0,
        urlPreSign: "/assets/images/sample_product.webp",
      },
    ],
    status: "active",
    rating: 4.5,
    stock: 10,
    sold: 2,
    description: {
      en: "ไส้กรอง Alkamag",
      th: "ไส้กรอง Alkamag",
    },
  },
];

export const fakeArticles: ArticlesType = [
  {
    title: "Articles 1",
    date: "29-04-2021",
    view: 1237,
    image: "/assets/images/article1.png",
  },
  {
    title: "Articles 2 Lorem ip sum sit amet",
    date: "29-05-2021",
    view: 1290,
    image: "/assets/images/article2.png",
  },
  {
    title: "Articles 3",
    date: "30-05-2021",
    view: 2290,
    image: "/assets/images/article3.png",
  },
  {
    title: "Articles 4",
    date: "30-05-2021",
    view: 2292,
    image: "/assets/images/article4.png",
  },
];

export const fakeBanners2: BannersType = [
  {
    desktopBanner: "/assets/images/banner2.png",
    tabletBanner: "/assets/images/banner2.png",
    mobileBanner: "/assets/images/banner2.png",
    hyperlink: "",
    position: 0,
    duration: 4,
  },
  {
    desktopBanner:
      "https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg",
    tabletBanner:
      "https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg",
    mobileBanner:
      "https://helpx.adobe.com/content/dam/help/en/photoshop/using/convert-color-image-black-white/jcr_content/main-pars/before_and_after/image-before/Landscape-Color.jpg",
    hyperlink: "",
    position: 0,
    duration: 4,
  },
];

export const fakeBanners3: BannersType = [
  {
    desktopBanner: "/assets/images/banner3.png",
    tabletBanner: "/assets/images/banner3.png",
    mobileBanner: "/assets/images/banner3.png",
    hyperlink: "",
    position: 0,
    duration: 4,
  },
  {
    desktopBanner:
      "https://jssors8.azureedge.net/demos/image-slider/img/px-beach-daylight-fun-1430675-image.jpg",
    tabletBanner:
      "https://jssors8.azureedge.net/demos/image-slider/img/px-beach-daylight-fun-1430675-image.jpg",
    mobileBanner:
      "https://jssors8.azureedge.net/demos/image-slider/img/px-beach-daylight-fun-1430675-image.jpg",
    hyperlink: "",
    position: 0,
    duration: 4,
  },
];
export const fakeBanners4: BannersType = [
  {
    desktopBanner: "/assets/images/banner4.png",
    tabletBanner: "/assets/images/banner4.png",
    mobileBanner: "/assets/images/banner4.png",
    hyperlink: "",
    position: 0,
    duration: 4,
  },
  {
    desktopBanner:
      "https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300",
    tabletBanner:
      "https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300",
    mobileBanner:
      "https://images.ctfassets.net/hrltx12pl8hq/7yQR5uJhwEkRfjwMFJ7bUK/dc52a0913e8ff8b5c276177890eb0129/offset_comp_772626-opt.jpg?fit=fill&w=800&h=300",
    hyperlink: "",
    position: 0,
    duration: 4,
  },
];
